version: '3.8'

services:
  resume-matcher-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_Kestrel__Limits__MaxRequestBodySize=52428800  # 50MB
    ports:
      - "80:80"   # Standard HTTP port for production
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/status/health"]
      interval: 60s
      timeout: 15s
      retries: 5
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'
    # Add security options for production
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp
      - /var/tmp 